---
# defaults file for build-disk
vyos_iso_file: "{{ iso }}"
vyos_iso_local: /tmp/vyos.iso
CD_ROOT: /mnt/cdrom
CD_SQUASH_ROOT: /mnt/cdsquash
SQUASHFS_IMAGE: "{{ CD_ROOT }}/live/filesystem.squashfs"

ESP_FSTYPE: vfat
ESP_PARTITION: "{{ volume_drive }}2"
ROOT_FSTYPE: ext4
ROOT_PARTITION: "{{ volume_drive }}3" # The install partition
volume_size: 4
volume_drive: /dev/xvdf
WRITE_ROOT: /mnt/wroot
READ_ROOT: /mnt/squashfs
INSTALL_ROOT: /mnt/inst_root
